export const PACK_PRESETS = {
  "character-actions": {
    kind: "sprite-actions",
    assetType: "character",
    style: "pixel",
    camera: "front",
    cell: [512, 512],
    columns: 4,
    rows: 1,
    shared: "same character identity, same costume and colors, one full-body sprite frame only, centered, plain solid background, no frame border",
    items: [
      {
        id: "idle",
        label: "Idle",
        prompt: "idle standing pose, relaxed ready stance",
        referenceDenoise: { stable: 0.38, balanced: 0.46, expressive: 0.54 },
      },
      {
        id: "walk",
        label: "Walk",
        prompt: "walk cycle key pose, one foot forward, arms offset, visible stepping motion, not idle",
        referenceDenoise: { stable: 0.58, balanced: 0.7, expressive: 0.82 },
      },
      {
        id: "attack",
        label: "Attack",
        prompt: "wide sword slash action pose, weapon extended, diagonal attack motion, dramatic torso turn, not idle",
        referenceDenoise: { stable: 0.66, balanced: 0.78, expressive: 0.88 },
      },
      {
        id: "hurt",
        label: "Hurt",
        prompt: "hurt reaction key pose, body recoiling backward, off-balance stance, defensive expression, not idle",
        referenceDenoise: { stable: 0.62, balanced: 0.74, expressive: 0.84 },
      },
    ],
  },
  "monster-actions": {
    kind: "sprite-actions",
    assetType: "creature",
    style: "pixel",
    camera: "front",
    cell: [512, 512],
    columns: 4,
    rows: 1,
    shared: "same creature identity, same colors and body shape, one centered monster sprite frame only, plain solid background, no frame border",
    items: [
      {
        id: "idle",
        label: "Idle",
        prompt: "idle monster pose, neutral expression",
        referenceDenoise: { stable: 0.38, balanced: 0.46, expressive: 0.54 },
      },
      {
        id: "move",
        label: "Move",
        prompt: "movement key pose, body squashed forward or stepping forward, clear motion, not idle",
        referenceDenoise: { stable: 0.58, balanced: 0.7, expressive: 0.82 },
      },
      {
        id: "attack",
        label: "Attack",
        prompt: "attack key pose, open mouth or striking appendage, aggressive forward motion, not idle",
        referenceDenoise: { stable: 0.66, balanced: 0.78, expressive: 0.88 },
      },
      {
        id: "death",
        label: "Death",
        prompt: "defeated collapse key pose, flattened or fallen body, readable silhouette, not idle",
        referenceDenoise: { stable: 0.62, balanced: 0.74, expressive: 0.84 },
      },
    ],
  },
  "skill-vfx": {
    kind: "sprite-actions",
    assetType: "vfx",
    style: "pixel",
    camera: "front",
    cell: [512, 512],
    columns: 4,
    rows: 1,
    shared: "same magical skill effect identity, centered VFX sprite frame only, plain solid chroma background, no character, no UI frame, no labels, consistent scale, readable looping sequence",
    items: [
      {
        id: "charge",
        label: "Charge",
        prompt: "charging anticipation frame, compact glowing core with small sparks gathering inward",
        referenceDenoise: { stable: 0.52, balanced: 0.62, expressive: 0.72 },
      },
      {
        id: "burst",
        label: "Burst",
        prompt: "energy burst frame, expanding ring and lightning arcs, strongest readable silhouette",
        referenceDenoise: { stable: 0.58, balanced: 0.7, expressive: 0.82 },
      },
      {
        id: "impact",
        label: "Impact",
        prompt: "impact peak frame, bright flash core, jagged sparks and flame tongues radiating outward",
        referenceDenoise: { stable: 0.62, balanced: 0.74, expressive: 0.86 },
      },
      {
        id: "fade",
        label: "Fade",
        prompt: "dissipating fade frame, fading embers, smaller arcs, readable loop back to charge",
        referenceDenoise: { stable: 0.56, balanced: 0.66, expressive: 0.76 },
      },
    ],
  },
  "ui-icons": {
    kind: "icon-pack",
    assetType: "icon",
    style: "pixel",
    camera: "front",
    cell: [512, 512],
    columns: 4,
    rows: 2,
    shared: "single inventory icon only, centered, no label text, no extra objects, plain solid background",
    items: [
      { id: "jade_sword", label: "Jade Sword", prompt: "jade sword inventory icon" },
      { id: "red_potion", label: "Red Potion", prompt: "red health potion bottle inventory icon" },
      { id: "shield", label: "Shield", prompt: "round steel shield inventory icon" },
      { id: "key", label: "Key", prompt: "gold key inventory icon" },
      { id: "coin", label: "Coin", prompt: "single gold coin inventory icon" },
      { id: "scroll", label: "Scroll", prompt: "rolled parchment scroll inventory icon" },
      { id: "gem", label: "Gem", prompt: "blue crystal gem inventory icon" },
      { id: "boot", label: "Boot", prompt: "leather boot inventory icon" },
    ],
  },
  "ui-kit": {
    kind: "ui-pack",
    assetType: "ui",
    style: "production",
    camera: "front",
    cell: [512, 512],
    columns: 4,
    rows: 2,
    shared: "single fantasy game UI component only, centered, no label text, no icon glyphs, plain solid chroma background, clean separable edges",
    items: [
      { id: "health_bar", label: "Health Bar", prompt: "horizontal health bar UI component with ornate frame and red fill area" },
      { id: "mana_bar", label: "Mana Bar", prompt: "horizontal mana bar UI component with ornate frame and blue fill area" },
      { id: "inventory_slot", label: "Inventory Slot", prompt: "square inventory slot frame UI component, empty center" },
      { id: "action_button", label: "Action Button", prompt: "round action button UI component, empty center, pressed-state friendly bevel" },
      { id: "dialog_panel", label: "Dialog Panel", prompt: "rectangular dialog panel UI component with decorative border and empty interior" },
      { id: "quest_panel", label: "Quest Panel", prompt: "compact quest tracker panel UI component with empty content area" },
      { id: "panel_corner", label: "Panel Corner", prompt: "ornate panel corner decoration UI component for nine-slice frames" },
      { id: "divider", label: "Divider", prompt: "thin decorative horizontal divider UI component" },
    ],
  },
  "map-tiles": {
    kind: "tile-pack",
    assetType: "map",
    style: "pixel",
    camera: "top-down",
    cell: [512, 512],
    columns: 4,
    rows: 2,
    shared: "single top-down orthographic square terrain tile only, seamless edges, no isometric camera, no horizon, no border, no labels",
    items: [
      { id: "grass", label: "Grass", prompt: "grass terrain tile" },
      { id: "dirt_road", label: "Dirt Road", prompt: "dirt road terrain tile" },
      { id: "stone_road", label: "Stone Road", prompt: "stone road terrain tile" },
      { id: "water_edge", label: "Water Edge", prompt: "grass to water edge terrain tile" },
      { id: "cliff", label: "Cliff", prompt: "top-down cliff edge terrain tile" },
      { id: "sand", label: "Sand", prompt: "sand terrain tile" },
      { id: "forest_floor", label: "Forest Floor", prompt: "forest floor terrain tile with small leaves" },
      { id: "lava_rock", label: "Lava Rock", prompt: "lava rock terrain tile" },
    ],
  },
};
